### ISSUE TITLE
Call out non-existent paths when attempting to archive

### ISSUE THREAD

**Issue by ethall** [ethall/syphon#11]
If you make a typo in the directory name, it is difficult to understand what went wrong.

Here's the output when I accidentally passed a path that didn't exist:
```
Traceback (most recent call last):
  File "C:\Python3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Source\syphon\syphon\__main__.py", line 79, in <module>
    exit(_main(argv))
  File "C:\Source\syphon\syphon\__main__.py", line 63, in _main
    archive(this_context)
  File "C:\Source\syphon\syphon\archive\archive.py", line 34, in archive
    lock_list.append(lock_manager.lock(split(data_list[0])[0]))
  File "C:\Python3\lib\site-packages\sortedcontainers\sortedlist.py", line 641, in __getitem__
    raise IndexError('list index out of range')
IndexError: list index out of range
```
Probably best to raise an exception before we try to create a lock file.

**Comment by ethall** [comment]
Migrated to https://github.com/tektronix/syphon/issues/2
